# Imagen base
FROM node:18

# Directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copiar solo package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar todo el código (será sobrescrito por el volumen en dev)
COPY . .

# Exponer el puerto de NestJS
EXPOSE 3000

# Comando para correr en modo desarrollo con watch
CMD ["npm", "run", "start:dev"]
